In [11]:
import datetime

In [12]:
data_li = pd.read_csv("data/상장폐지현황_.csv", encoding = 'CP949')
data_li.head(3)

,번호,회사명,종목코드,폐지일자,폐지사유,비고
0,1272,바이오빌,65940,2020-07-31,감사의견 거절(감사범위 제한 및 계속기업 존속능력에 대한 불확실성),NaN
1,1271,이엔드디,101360,2020-07-30,코스닥시장 이전상장,이엔드디
2,1270,한국제6호스팩,281410,2020-07-27,상장예비심사 청구서 미제출로 관리종목 지정 후 1개월 이내 동 사유 미해소,NaN

In [13]:
data_lis = data_li.loc[data_li['폐지사유'].str.contains('부도')]
data_list = data_lis.iloc[:,[1,3]]
data_list.head(3)

       회사명        폐지일자
50    데코앤이  2019-11-20
82      신텍  2018-07-09
119  금오하이텍  2017-06-07

In [14]:
data_list['폐지일자'] = data_list['폐지일자'].str.replace('-','')
data_list = data_list.reset_index(drop = True)
data_list.columns = ['company', 'date']
print(data_list.shape)
data_list.head(3)

C:\Users\14\.conda\envs\tf2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

(70, 2)

  company      date
0    데코앤이  20191120
1      신텍  20180709
2   금오하이텍  20170607

In [15]:
com_df = pd.read_csv('data/bankrup_list.csv')
print(com_df.shape)
com_df.head(3)

(439, 2)

                     company      date
0  (유)동해건업                    20190403
1    (유)부강산업개발                20181017
2    (유)세일디앤아이                20190110

In [16]:
com_list = pd.concat([data_list, com_df])
com_list.reset_index(drop = True)
com_list['company'] = com_list['company'].str.replace(" ", "")
print(com_list.shape)
com_list.head(3)

(509, 2)

  company      date
0    데코앤이  20191120
1      신텍  20180709
2   금오하이텍  20170607

In [21]:
com_list

        company      date
0          데코앤이  20191120
1            신텍  20180709
2         금오하이텍  20170607
3        에이치앤아이  20160714
4         티에스엠텍  20150520
..          ...       ...
434  홍익엔지니어링(주)  20190402
435     홍주실업(주)  20181024
436     화신산업(주)  20191126
437   효진종합건설(주)  20181204
438        JS무역  20180907

[509 rows x 2 columns]

In [29]:
com_list['date'] = com_list['date'].astype(str)

In [30]:
com_list['date'].str[0:4].value_counts()

2019    318
2018    123
2004     10
2002      8
2005      8
2003      8
2010      7
2000      7
2012      5
1999      4
2009      2
2008      2
2015      2
2006      1
2011      1
2017      1
2001      1
2016      1
Name: date, dtype: int64

In [161]:
com_list.to_csv('data/com_list.csv', index = False)

In [164]:
len(com_list['company'])

509

In [172]:
have_list = []
no_list = []
for li in com_list['company']:
    try:
        basic_info = crp_list.find_by_corp_name(li, exactly=True)[0]
        have_list.append(li)
    except:
        no_list.append(li)

In [173]:
print(len(have_list))
have_list

55

['데코앤이',
 '신텍',
 '금오하이텍',
 '에이치앤아이',
 '티에스엠텍',
 '우양에이치씨',
 '배명금속',
 '금강제강',
 '풍림산업',
 '미주제강',
 '제이콤',
 '인네트',
 '신세계톰보이',
 '에스피코프',
 '쌈지',
 '카라반케이디이',
 '유리이에스',
 '아이비진',
 '우영',
 '알루코',
 '케이티씨텔레콤',
 '아이텍스필',
 '현주컴퓨터',
 '넥스텔',
 '지에스엔텍',
 '현대멀티캡',
 '중앙제지',
 '테크메이트',
 '텔슨전자',
 '금강화섬',
 '호성',
 '대호',
 '모닷텔',
 '화림모드',
 '서통',
 '계몽사',
 '코리아링크',
 '시스컴',
 '정산애강',
 '소프트윈',
 '심스밸리',
 '코닉스',
 '유니씨앤티',
 '아이씨켐',
 '디지텔',
 '삼한콘트롤스',
 '피어리스',
 '정일이엔씨',
 '삼산',
 '교하산업',
 '아진산업',
 '주화산업',
 '라인건설',
 '대륭산업',
 '한국종합철관']

In [174]:
print(len(no_list))
no_list

454

['SSCP',
 '하이드로젠파워',
 '케이씨오에너지',
 'GK파워',
 'VK',
 '영창악기제조',
 '동아정기',
 '대흥멀티통신',
 'KNC',
 '다산씨앤아이',
 '이론테크',
 '화인썬트로닉스',
 '대한종금',
 '한국대아진공',
 '영성제강',
 '(유)동해건업',
 '(유)부강산업개발',
 '(유)세일디앤아이',
 '(유)장수',
 '(의)서구의료재단여수성심병원',
 '(의)성실의료재단창녕요양병원',
 '(의)원의료재단동김해병원',
 '(주)ENS',
 '(주)JBM',
 '(주)거성합판목재',
 '(주)거연',
 '(주)거진상역',
 '(주)건형설비',
 '(주)경상엔지니어링',
 '(주)경안전선',
 '(주)경은',
 '(주)경천에스앤디',
 '(주)계진푸드',
 '(주)고려이알피',
 '(주)고려전기상사',
 '(주)관동물산',
 '(주)광명인치코리아',
 '(주)광진엔지니어링',
 '(주)광진종합물류',
 '(주)그린라이트',
 '(주)그린비',
 '(주)그린위드',
 '(주)그린플러스',
 '(주)글로벌리더스',
 '(주)금강골재',
 '(주)금빛식자재마트',
 '(주)금상종합주류',
 '(주)길상유통',
 '(주)나무와사람들',
 '(주)나우물산',
 '(주)나우상사',
 '(주)남윤산업',
 '(주)네오센스',
 '(주)뉴골드마인',
 '(주)뉴한일산업',
 '(주)님프만',
 '(주)다스코리아',
 '(주)다영산업개발',
 '(주)대건내츄럴',
 '(주)대건에프앤비',
 '(주)대경공영',
 '(주)대도건영',
 '(주)대림종합건설',
 '(주)대산씨에스에이',
 '(주)대상이엔지',
 '(주)대성',
 '(주)대양인터네셔널',
 '(주)대정설비',
 '(주)대진인더스트리',
 '(주)대한동력케이블',
 '(주)대한티앤피',
 '(주)대현산업',
 '(주)대화연료펌프',
 '(주)더에스앤에이치',
 '(주)더좋은푸드',
 '(주)더플랜',
 '(주)덕양상사',
 '(주)덕유',
 '(주)데코앤이',
 '(주)동경',
 '(주)동광오알티',
 '(주)동보철강',
 '(주)동성',
 '(주)동양프라텍',
 '(주)동영씨푸트',
 '(주)동오성',
 '(주)동오프랜지',
 '(주)동일월드',
 '(주)동진약품',
 '(주)동진주공',
 '(주)두리성',
 '(주)두산해운',
 '(주)디에스팩',
 '(주)디에이치메탈',
 '(주)디엠케이',
 '(주)디자인인터',
 '(주)뜨레비디엔씨',
 '(주)라이브론',
 '(주)라이트제림',
 '(주)로얄마트',
 '(주)마스타인터내셔날',
 '(주)마스타텍',
 '(주)마이웨이',
 '(주)마하',
 '(주)매일통상',
 '(주)명진농축산',
 '(주)명진종합건설',
 '(주)모터월드',
 '(주)모티브',
 '(주)미가',
 '(주)미건의료기',
 '(주)미건이엔씨',
 '(주)미드림',
 '(주)미르산업개발',
 '(주)미르전기',
 '(주)바쁜손유통',
 '(주)바우주택건설',
 '(주)반도케미칼',
 '(주)범진종합건설',
 '(주)베가',
 '(주)베델',
 '(주)보성해우소',
 '(주)부광종합건설',
 '(주)부흥산업',
 '(주)비젼케이엔에스',
 '(주)빠라베에사',
 '(주)삼부산업',
 '(주)삼성에이치앤비',
 '(주)삼우네오텍',
 '(주)삼원이피에스',
 '(주)삼협정밀',
 '(주)상일실업',
 '(주)상지이엔지',
 '(주)새한폴리머',
 '(주)서린주택',
 '(주)서신엔지니어링',
 '(주)서원상사',
 '(주)서일엠이씨',
 '(주)서평종합건설',
 '(주)서해에스에프씨',
 '(주)석영',
 '(주)성도',
 '(주)성도이앤씨',
 '(주)성우씨앤에프',
 '(주)성원물산',
 '(주)성원철강',
 '(주)성일하이테크',
 '(주)성지아트',
 '(주)성진메탈테크',
 '(주)성진화학',
 '(주)성창기업',
 '(주)성토건설',
 '(주)세광정밀',
 '(주)세교하이텍',
 '(주)세림에코',
 '(주)세영통상',
 '(주)세원금속',
 '(주)세일섬유',
 '(주)세진씨엔비',
 '(주)세코',
 '(주)세한건설',
 '(주)소년한국일보',
 '(주)솔목',
 '(주)수진산업개발',
 '(주)수호전기',
 '(주)순수화장품',
 '(주)스틸앤맨',
 '(주)시스네트',
 '(주)신광대리석',
 '(주)신라바스',
 '(주)신성에프엔씨',
 '(주)신세명',
 '(주)신영기업',
 '(주)신우엘에스산업',
 '(주)신진',
 '(주)신천',
 '(주)신화씨.엔.지',
 '(주)쌍용영월산기',
 '(주)써니',
 '(주)썬케이',
 '(주)씨엔에스인터',
 '(주)아림지앤코',
 '(주)아산이엔씨',
 '(주)아이피티',
 '(주)아트참',
 '(주)알파에스엠코리아',
 '(주)양원산업',
 '(주)에스아이테크',
 '(주)에스에스종합물류',
 '(주)에스에스텍스타일',
 '(주)에스에이치(SH)',
 '(주)에이스팜',
 '(주)엔에이치티',
 '(주)엔이더블유미래로',
 '(주)엘루',
 '(주)엘큐코리아',
 '(주)엠플러스쇼핑',
 '(주)영수산유통',
 '(주)영신칼스토리',
 '(주)영정물산',
 '(주)영지피엠씨',
 '(주)영진교역',
 '(주)영창레포츠',
 '(주)오로라유통',
 '(주)오산농민마트',
 '(주)오에이치',
 '(주)올리앤올슨',
 '(주)용전',
 '(주)우농이엔지',
 '(주)우리종합',
 '(주)우성아이비',
 '(주)우정건설산업',
 '(주)우정기획',
 '(주)우주상사',
 '(주)울성상사',
 '(주)웅지이엔지',
 '(주)원파워',
 '(주)윈테코',
 '(주)유건',
 '(주)유동에프씨',
 '(주)유승상사',
 '(주)은성개발',
 '(주)을지',
 '(주)이동수에프엔지',
 '(주)이솔유통',
 '(주)이엔산업',
 '(주)이화실업',
 '(주)인성',
 '(주)인성에프앤피',
 '(주)인일산업',
 '(주)인플랜',
 '(주)일만물유통',
 '(주)일선상사',
 '(주)일성유통',
 '(주)일신마린써비스',
 '(주)일진호이스트크레인',
 '(주)재연상사',
 '(주)정명케이블',
 '(주)정안산업',
 '(주)정일개발',
 '(주)정일기업',
 '(주)정일산업',
 '(주)정한섬유',
 '(주)제이앤컴퍼니',
 '(주)제이앤피무역',
 '(주)제이에이치무역',
 '(주)제이엔테크',
 '(주)제이와이인송산업',
 '(주)조일마트',
 '(주)지가캡',
 '(주)지앤케이',
 '(주)지엔비',
 '(주)지향',
 '(주)진미산업',
 '(주)진산종합중기',
 '(주)참다운푸드',
 '(주)창영비앤비',
 '(주)창원자동차학원',
 '(주)챔피온',
 '(주)첨단부품',
 '(주)청솔식품',
 '(주)청정에드원',
 '(주)초록이노텍',
 '(주)초록푸드시스템',
 '(주)충언건영',
 '(주)커먼컴',
 '(주)케이비현앤장',
 '(주)코리아산업',
 '(주)코빅건설',
 '(주)코지',
 '(주)코튼코리아',
 '(주)크린랩라텍스',
 '(주)타임스포츠',
 '(주)탐라',
 '(주)태성건설',
 '(주)태승섬유',
 '(주)태양그로윙',
 '(주)태우테크',
 '(주)태정아이엔디',
 '(주)태천',
 '(주)태화석재',
 '(주)태화화스너',
 '(주)테이크씨',
 '(주)통일목재',
 '(주)티엠코리아',
 '(주)티케이씨',
 '(주)퍼펙트마케팅',
 '(주)평산유통',
 '(주)풍산디에스',
 '(주)플러스디자인',
 '(주)플러스인테리어디자인',
 '(주)피알',
 '(주)피플엠',
 '(주)필아테크',
 '(주)하나마트',
 '(주)하이스코',
 '(주)하이테크노쎌',
 '(주)하이파오피스',
 '(주)학표벽지',
 '(주)한건티엔씨',
 '(주)한국세륜기',
 '(주)한라엠케이산업',
 '(주)한백에프앤씨',
 '(주)한양전선',
 '(주)한일세미컴',
 '(주)한일의료기',
 '(주)한일전기',
 '(주)해피로이앤씨',
 '(주)핸즈이노베이션',
 '(주)현경이엔씨',
 '(주)현대산기',
 '(주)현대유리',
 '(주)현대패널',
 '(주)호산세라믹스',
 '(주)화산',
 '(주)화성스틸판넬',
 '(주)화신산업',
 '(주)화인토일리트리',
 '(주)화제신문',
 '(주)황성산업',
 '(주)흥해종합건설',
 '(주)흥화',
 '<주>한미프렉시블',
 'HHICPHILKOREA주식회사',
 '강일약품(주)',
 '거원산업(주)',
 '건양개발주식회사',
 '국도골재(합자)',
 '굿모닝기룡건설(주)',
 '극동택시(주)',
 '금아기전(주)',
 '금정제십이차(주)',
 '금호기술(주)',
 '기영엔지니어링<주>',
 '기영항업(주)',
 '나인주택건설(주)',
 '농업법인(주)더부러',
 '농업회사법인(유)미',
 '농업회사법인(주)건농',
 '농업회사법인(주)대용축산',
 '농업회사법인(주)보금',
 '농업회사법인(주)지천글로벌',
 '농업회사법인(주)청풍미트',
 '농업회사법인킹스테이블(주)',
 '대경안전유리(주)',
 '대덕이엔씨(주)',
 '대동커튼월(주)',
 '대명산업(주)',
 '대선건설(주)',
 '대성전력(주)',
 '대아정공(주)',
 '대양영농조합',
 '대양주류(유)',
 '대영종합건설(주)',
 '대유중공업(주)',
 '대유플랜트(주)',
 '대은주류(주)',
 '대익건설(주)',
 '대한강재(주)',
 '대화공영(주)',
 '덕수철강(주)',
 '도량기업(주)',
 '동명건설(주)',
 '동북건설<주>',
 '동신수산(주)',
 '동아화이어테크(주)',
 '디엑스스퀘어드(주)',
 '라인씨스템(주)',
 '명성약품(주)',
 '미다스(주)',
 '미래공조플랜트(주)',
 '미래실업(주)',
 '미래파트너스(주)',
 '미소건설(주)',
 '배성물산(주)',
 '부광엔지니어링(주)',
 '부울경산업(주)',
 '비엠글로벌(주)',
 '상보건설(주)',
 '서진설비(주)',
 '서현스틸(주)',
 '석달(주)',
 '선우산업(주)',
 '성명산업(유)',
 '세원건설(주)',
 '세원목재(주)',
 '세존상사(주)',
 '신평유기(주)',
 '신흥설비(주)',
 '아강테크(주)',
 '아이타올(주)',
 '안동석건(주)',
 '안동석재산업(주)',
 '에스에이에스(주)',
 '에스에이치엠(주)',
 '에이티아이유통(주)',
 '엠앤에스산업(주)',
 '엠에이치건설(주)',
 '영지산업(주)',
 '영창건업(주)',
 '와일드마운틴(주)',
 '용마철강(주)',
 '우리이엔씨(주)',
 '우주소방전기(주)',
 '우진중공업(주)',
 '위더스앤플랜(주)',
 '위캔글로벌(주)',
 '유복전기(주)',
 '유승종합건설(주)',
 '율원약품(주)',
 '의료법인성석의료재단',
 '의료법인애민의료재단',
 '이선케이블(주)',
 '이오제이이앤씨(주)',
 '일성전장(주)',
 '재영실업(주)',
 '정석건업(주)',
 '제이알철강(주)',
 '제이엠유통(주)',
 '주)태백광업',
 '지웅전기(주)',
 '진우창호(주)',
 '철인종합건설(주)',
 '청솔아이엔에스(주)',
 '칼텍(주)',
 '케이디데니스패션(주)',
 '케이씨피(주)',
 '케이아이유통(주)',
 '케이엠에프(주)',
 '코리아팜(주)',
 '탐라도서(주)',
 '태경산업개발(주)',
 '토고(주)',
 '통일경제(주)',
 '통일운수(합자)',
 '피알캠(주)',
 '하이코건설(주)',
 '한겨레건설(주)',
 '한국마그넷(주)',
 '한국메디케어(주)',
 '한독건설(주)',
 '한성기업<주>',
 '한성약품(주)',
 '한성엔지니어링(주)',
 '한아종합기술(주)',
 '한영콘트롤(주)',
 '한일엠이써비스(주)',
 '한일전설(주)',
 '호산이엔지(주)',
 '홍익엔지니어링(주)',
 '홍주실업(주)',
 '화신산업(주)',
 '효진종합건설(주)',
 'JS무역']

In [181]:
print('부도기업:', len(com_list))
print('조회가능 기업:',len(have_list))
print('조회불가 기업:',len(no_list))

부도기업: 509
조회가능 기업: 55
조회불가 기업: 454

In [1]:
import dart_fss as dart
import pandas as pd

In [2]:
api_key='7bba91f51399cd6256c184c5ad0b2539c0bfd8b6'
dart.set_api_key(api_key=api_key)

'7bba91f51399cd6256c184c5ad0b2539c0bfd8b6'

In [3]:
crp_list = dart.get_corp_list()

Output()

Output()

Output()

In [9]:
len(crp_list.find_by_product(product = '제조', market = 'K'))

84

In [44]:
basic_info = crp_list.find_by_corp_name('배명금속', exactly=True)[0]

In [45]:
fs = basic_info.extract_fs(bgn_de='20190101')

RuntimeError: Could not find an annual report

In [46]:
# 'bs' 재무상태표, 'is' 손익계산서, 'cis' 포괄손익계산서, 'cf' 현금흐름표
df_cis = fs['cis']
df_bs = fs['bs']
df_cf = fs['cf']

In [47]:
df_cis.head(3)

  [D431410] Statement of comprehensive income, by function of expense - Consolidated financial statements (Unit: KRW)  \
                                                                                                           concept_id
0                                  ifrs-full_Revenue
1                              ifrs-full_CostOfSales
2                              ifrs-full_GrossProfit

                                                                     \
  label_ko        label_en              class0 class1 class2 class3
0      매출액  Revenue(Sales)  포괄손익계산서 [abstract]    매출액   None   None
1     매출원가   Cost of sales  포괄손익계산서 [abstract]   매출원가   None   None
2    매출총이익    Gross profit  포괄손익계산서 [abstract]  매출총이익   None   None

  20190101-20191231 20180101-20181231 20170101-20171231
          (연결재무제표,)         (연결재무제표,)         (연결재무제표,)
0  12,690,903,987.0  26,187,470,807.0  14,262,299,673.0
1  12,607,067,912.0  24,916,951,370.0  15,083,677,830.0
2      83,836,075.0   1,270,519,437.0    -821,378,157.0

In [182]:
df_cis.to_csv('data/포괄손익계산서.csv', index = False)

In [62]:
df_cis.shape

(22, 9)

In [46]:
df_cis_1 = df_cis.iloc[:,[1,7,8,9,10,11,12,13,14,15,16]]
df_cis_1.head()

,"[D431410] Statement of comprehensive income, by function of expense - Consolidated financial statements (Unit: KRW)",20190101-20191231,20180101-20181231,20170101-20171231,20160101-20161231,20150101-20151231,20140101-20141231,20130101-20131231,20120101-20121231,20110101-20111231,20100101-20101231
,label_ko,"(연결재무제표,)","(연결재무제표,)","(연결재무제표,)","(연결재무제표,)","(연결재무제표,)","(연결재무제표,)","(연결재무제표,)","(연결재무제표,)","(연결재무제표,)","(연결재무제표,)"
0,매출액,"12,690,903,987.0","26,187,470,807.0","14,262,299,673.0","32,103,083,828.0","45,842,816,368.0","38,727,177,238.0","15,196,232,949.0","13,685,959,634.0","21,407,573,560.0","5,637,764,074.0"
1,매출원가,"12,607,067,912.0","24,916,951,370.0","15,083,677,830.0","29,662,212,933.0","40,620,122,702.0","33,420,478,831.0","-11,072,077,092.0","-13,103,130,950.0","-18,739,373,700.0","-5,639,981,037.0"
2,매출총이익,"83,836,075.0","1,270,519,437.0","-821,378,157.0","2,440,870,895.0","5,222,693,666.0","5,306,698,407.0","4,124,155,857.0","582,828,684.0","2,668,199,860.0","-2,216,963.0"
3,판매비와관리비,"3,863,460,724.0","5,214,421,708.0","6,019,047,667.0","6,249,655,629.0","5,077,369,911.0","5,367,160,596.0","-6,078,626,493.0","-1,697,360,236.0","-1,123,965,503.0","-4,416,574,142.0"
4,영업이익(손실),"-3,779,624,649.0","-3,943,902,271.0","-6,840,425,824.0",None,"145,323,755.0","-60,462,189.0","-1,954,470,636.0","-1,114,531,552.0","1,612,187,512.0","-4,300,784,250.0"

In [47]:
df_cis_1.shape

(35, 11)

In [56]:
df_cis_1.columns = ['label', df_cis_1.columns[1][0], df_cis_1.columns[2][0], df_cis_1.columns[3][0], df_cis_1.columns[4][0], df_cis_1.columns[5][0], df_cis_1.columns[6][0], df_cis_1.columns[7][0], df_cis_1.columns[8][0], df_cis_1.columns[9][0], df_cis_1.columns[10][0]]

In [57]:
df_cis_1.head(5)

,label,20190101-20191231,20180101-20181231,20170101-20171231,20160101-20161231,20150101-20151231,20140101-20141231,20130101-20131231,20120101-20121231,20110101-20111231,20100101-20101231
0,매출액,"12,690,903,987.0","26,187,470,807.0","14,262,299,673.0","32,103,083,828.0","45,842,816,368.0","38,727,177,238.0","15,196,232,949.0","13,685,959,634.0","21,407,573,560.0","5,637,764,074.0"
1,매출원가,"12,607,067,912.0","24,916,951,370.0","15,083,677,830.0","29,662,212,933.0","40,620,122,702.0","33,420,478,831.0","-11,072,077,092.0","-13,103,130,950.0","-18,739,373,700.0","-5,639,981,037.0"
2,매출총이익,"83,836,075.0","1,270,519,437.0","-821,378,157.0","2,440,870,895.0","5,222,693,666.0","5,306,698,407.0","4,124,155,857.0","582,828,684.0","2,668,199,860.0","-2,216,963.0"
3,판매비와관리비,"3,863,460,724.0","5,214,421,708.0","6,019,047,667.0","6,249,655,629.0","5,077,369,911.0","5,367,160,596.0","-6,078,626,493.0","-1,697,360,236.0","-1,123,965,503.0","-4,416,574,142.0"
4,영업이익(손실),"-3,779,624,649.0","-3,943,902,271.0","-6,840,425,824.0",None,"145,323,755.0","-60,462,189.0","-1,954,470,636.0","-1,114,531,552.0","1,612,187,512.0","-4,300,784,250.0"

In [37]:
df_n

In [29]:
df_cis_1.columns[1][0]

'20190101-20191231'

In [82]:
df_bs

   [D220000] Statement of financial position, order of liquidity - Consolidated financial statements (Unit: KRW)  \
                                                                                                      concept_id
0                         ifrs_CashAndCashEquivalents
1                           ifrs_OtherFinancialAssets
2                       ifrs_TradeAndOtherReceivables
3                               ifrs_CurrentTaxAssets
4                                    ifrs_Inventories
5   entity00122339_udf_BS_201332115352562_AssetsAb...
6   entity00122339_udf_BS_2013321153522406_AssetsA...
7   entity00122339_udf_BS_2014325112015353_AssetsA...
8        ifrs_InvestmentAccountedForUsingEquityMethod
9                      ifrs_PropertyPlantAndEquipment
10  entity00122339_udf_BS_2016328133622823_AssetsA...
11                                 dart_GoodwillGross
12                             ifrs_DeferredTaxAssets
13                       ifrs_OtherNonfinancialAssets
14                                        ifrs_Assets
15                         ifrs_TradeAndOtherPayables
16                                    ifrs_Borrowings
17  entity00122339_udf_BS_2013827153445698_Liabili...
18                         ifrs_CurrentTaxLiabilities
19  entity00122339_udf_BS_2013321154319500_Liabili...
20  entity00122339_udf_BS_2013321154254796_Liabili...
21  entity00122339_udf_BS_2016328134028811_Liabili...
22                        ifrs_DeferredTaxLiabilities
23                                   ifrs_Liabilities
24  entity00122339_udf_BS_2014828215446174_Stateme...
25                             dart_ContributedEquity
26                              ifrs_RetainedEarnings
27             dart_ElementsOfOtherStockholdersEquity
28  entity00122339_udf_BS_2014325111911720_EquityA...
29  entity00122339_udf_BS_201533191723495_EquityAb...
30  entity00122339_udf_BS_201332116240265_EquityAb...
31                       ifrs_NoncontrollingInterests
32                                        ifrs_Equity
33                          ifrs_EquityAndLiabilities

                                                                      \
         label_ko                                           label_en
0        현금및현금성자산                          Cash and cash equivalents
1          단기금융상품                             Other financial assets
2     매출채권 및 기타채권                        Trade and other receivables
3         당기법인세자산                                 Current tax assets
4            재고자산                                        Inventories
5          기타유동자산                          NEWAccount for Assets (1)
6   장기매출채권 및 기타채권                          NEWAccount for Assets (2)
7          장기금융자산                          NEWAccount for Assets (3)
8      지분법적용 투자지분      Investments accounted for using equity method
9            유형자산                      Property, plant and equipment
10           무형자산                          NEWAccount for Assets (4)
11            영업권                                    Goodwill, gross
12        이연법인세자산                                Deferred tax assets
13        기타비유동자산                         Other non-financial assets
14           자산총계                                       Total assets
15    매입채무 및 기타채무                           Trade and other payables
16         단기금융부채                                         Borrowings
17         기타유동부채                     NEWAccount for Liabilities (4)
18        당기법인세부채                            Current tax liabilities
19         장기금융부채                     NEWAccount for Liabilities (3)
20  장기매입채무 및 기타채무                     NEWAccount for Liabilities (2)
21        기타비유동부채                     NEWAccount for Liabilities (5)
22        이연법인세부채                           Deferred tax liabilities
23           부채총계                                  Total liabilities
24    지배기업의 소유주지분  NEWAccount for Statement of financial position...
25            자본금                                 Contributed equity
26          자본잉여금                                  Retained earnings
27       기타자본구성요소          Elements of other stockholder's equity
28           자본조정                          NEWAccount for Equity (2)
29      기타포괄손익누계액                          NEWAccount for Equity (3)
30            결손금                          NEWAccount for Equity (1)
31          비지배지분                          Non-controlling interests
32           자본총계                                       Total equity
33        자본과부채총계                       Total equity and liabilities

                                                             20160630  \
              class0          class1         class2         (연결재무제표,)
0   재무상태표 [abstract]   자산 [abstract]       현금및현금성자산   1,873,070,192.0
1   재무상태표 [abstract]   자산 [abstract]         단기금융상품  18,615,655,695.0
2   재무상태표 [abstract]   자산 [abstract]    매출채권 및 기타채권   6,420,330,957.0
3   재무상태표 [abstract]   자산 [abstract]        당기법인세자산      40,226,214.0
4   재무상태표 [abstract]   자산 [abstract]           재고자산              None
5   재무상태표 [abstract]   자산 [abstract]         기타유동자산   3,238,331,276.0
6   재무상태표 [abstract]   자산 [abstract]  장기매출채권 및 기타채권     812,741,356.0
7   재무상태표 [abstract]   자산 [abstract]         장기금융자산   2,585,698,341.0
8   재무상태표 [abstract]   자산 [abstract]     지분법적용 투자지분              None
9   재무상태표 [abstract]   자산 [abstract]           유형자산     376,638,518.0
10  재무상태표 [abstract]   자산 [abstract]           무형자산     210,964,613.0
11  재무상태표 [abstract]   자산 [abstract]            영업권              None
12  재무상태표 [abstract]   자산 [abstract]        이연법인세자산              None
13  재무상태표 [abstract]   자산 [abstract]        기타비유동자산     933,265,003.0
14  재무상태표 [abstract]   자산 [abstract]           자산총계  35,106,922,165.0
15  재무상태표 [abstract]  부채  [abstract]    매입채무 및 기타채무   4,191,340,495.0
16  재무상태표 [abstract]  부채  [abstract]         단기금융부채   4,709,681,046.0
17  재무상태표 [abstract]  부채  [abstract]         기타유동부채   3,225,954,605.0
18  재무상태표 [abstract]  부채  [abstract]        당기법인세부채              None
19  재무상태표 [abstract]  부채  [abstract]         장기금융부채      37,740,852.0
20  재무상태표 [abstract]  부채  [abstract]  장기매입채무 및 기타채무      58,828,333.0
21  재무상태표 [abstract]  부채  [abstract]        기타비유동부채              None
22  재무상태표 [abstract]  부채  [abstract]        이연법인세부채
23  재무상태표 [abstract]  부채  [abstract]           부채총계  12,223,545,331.0
24  재무상태표 [abstract]     지배기업의 소유주지분           None  22,988,828,676.0
25  재무상태표 [abstract]   자본 [abstract]            자본금              None
26  재무상태표 [abstract]   자본 [abstract]          자본잉여금              None
27  재무상태표 [abstract]   자본 [abstract]       기타자본구성요소              None
28  재무상태표 [abstract]   자본 [abstract]           자본조정              None
29  재무상태표 [abstract]   자본 [abstract]      기타포괄손익누계액              None
30  재무상태표 [abstract]   자본 [abstract]            결손금 -46,641,078,027.0
31  재무상태표 [abstract]   자본 [abstract]          비지배지분    -105,451,842.0
32  재무상태표 [abstract]   자본 [abstract]           자본총계  22,883,376,834.0
33  재무상태표 [abstract]         자본과부채총계           None  35,106,922,165.0

            20151231          20141231          20131231
           (연결재무제표,)         (연결재무제표,)         (연결재무제표,)
0    5,815,263,717.0   3,589,220,796.0   1,165,303,369.0
1    6,276,609,215.0   2,914,222,887.0   2,781,473,542.0
2    5,935,747,431.0   6,898,258,930.0   6,112,434,850.0
3      112,943,974.0       2,268,910.0      19,433,707.0
4        9,724,134.0      11,645,916.0      48,193,443.0
5   10,001,489,690.0  10,500,088,535.0   3,609,013,595.0
6    6,145,076,620.0   2,523,099,332.0   2,109,139,673.0
7      117,448,551.0     124,088,116.0      34,421,165.0
8                nan               nan      33,158,953.0
9    6,470,095,912.0     263,139,754.0     332,033,064.0
10   7,845,115,943.0   4,174,249,916.0   4,225,443,266.0
11               nan               nan               nan
12      44,530,483.0      84,970,213.0      54,461,777.0
13   1,974,506,429.0   3,463,528,265.0   2,180,555,556.0
14  50,748,552,099.0  34,548,781,570.0  22,705,065,960.0
15  10,308,915,409.0  11,680,035,731.0   5,515,370,037.0
16   8,826,143,677.0   8,622,192,615.0   6,228,784,584.0
17   5,946,031,738.0   3,652,155,603.0   2,297,136,242.0
18     231,428,335.0     276,320,741.0               0.0
19   6,035,571,219.0               nan               0.0
20     180,993,528.0     244,478,997.0     146,040,299.0
21       5,044,931.0      82,387,571.0               nan
22       4,286,110.0               nan               nan
23  31,538,414,947.0  24,557,571,258.0  14,187,331,162.0
24  18,479,278,343.0  10,093,827,206.0   8,537,355,751.0
25   8,481,688,500.0   6,616,257,500.0   5,404,422,000.0
26  56,995,377,393.0  46,381,768,096.0  43,220,403,678.0
27               nan               nan               0.0
28    -357,000,000.0    -357,000,000.0    -357,000,000.0
29               0.0     373,500,000.0               0.0
30 -46,640,787,550.0 -42,920,698,390.0 -39,730,469,927.0
31     730,858,809.0    -102,616,894.0     -19,620,953.0
32  19,210,137,152.0   9,991,210,312.0   8,517,734,798.0
33  50,748,552,099.0  34,548,781,570.0  22,705,065,960.0

In [183]:
df_bs.to_csv('data/재무상태표.csv', index = False)

In [58]:
df_bs.shape

(31, 21)

In [83]:
df_cf

   [D520000] Statement of cash flows, indirect method - Consolidated financial statements (Unit: KRW)  \
                                                                                           concept_id
0         ifrs_CashFlowsFromUsedInOperatingActivities
1              dart_ProfitLossForStatementOfCashFlows
2              ifrs_AdjustmentsForReconcileProfitLoss
3   dart_AdjustmentsForProvisionForSeveranceIndemn...
4              dart_AdjustmentsForDepreciationExpense
..                                                ...
87  entity00122339_udf_CF_2016328194116304_CashFlo...
88      ifrs_IncreaseDecreaseInCashAndCashEquivalents
89   dart_CashAndCashEquivalentsAtBeginningOfPeriodCf
90  entity00122339_udf_CF_201482912173479_Statemen...
91         dart_CashAndCashEquivalentsAtEndOfPeriodCf

                                                                              \
                 label_ko                                           label_en
0                영업활동현금흐름     Cash flows from (used in) operating activities
1               당기순이익(손실)                                      Profit (loss)
2          당기순이익조정을 위한 가감             Adjustments to reconcile profit (loss)
3                    퇴직급여  Adjustments for Provision for severance indemn...
4                   감가상각비               Adjustments for depreciation expense
..                    ...                                                ...
87            프로젝트예수금의 감소  NEWAccount for Cash flows from (used in) finan...
88       현금및현금성자산의순증가(감소)  Net increase (decrease) in cash and cash equiv...
89             기초현금및현금성자산   Cash and cash equivalents at beginning of period
90  연결대상범위 변동으로 인한 현금의 증감         NEWAccount for Statement of cash flows (1)
91             기말현금및현금성자산         Cash and cash equivalents at end of period

                                                                    \
              class0                 class1          class2 class3
0   현금흐름표 [abstract]               영업활동현금흐름            None   None
1   현금흐름표 [abstract]               영업활동현금흐름       당기순이익(손실)   None
2   현금흐름표 [abstract]               영업활동현금흐름  당기순이익조정을 위한 가감   None
3   현금흐름표 [abstract]               영업활동현금흐름  당기순이익조정을 위한 가감   퇴직급여
4   현금흐름표 [abstract]               영업활동현금흐름  당기순이익조정을 위한 가감  감가상각비
..               ...                    ...             ...    ...
87  현금흐름표 [abstract]               재무활동현금흐름     프로젝트예수금의 감소   None
88  현금흐름표 [abstract]       현금및현금성자산의순증가(감소)            None   None
89  현금흐름표 [abstract]             기초현금및현금성자산            None   None
90  현금흐름표 [abstract]  연결대상범위 변동으로 인한 현금의 증감            None   None
91  현금흐름표 [abstract]             기말현금및현금성자산            None   None

   20160101-20160630 20150101-20151231 20150101-20150630 20140101-20141231  \
           (연결재무제표,)         (연결재무제표,)         (연결재무제표,)         (연결재무제표,)
0      514,127,716.0   1,026,766,886.0     836,192,201.0  -6,469,669,899.0
1      807,302,163.0  -3,021,722,219.0  -2,301,645,719.0  -3,198,747,958.0
2        6,121,257.0   4,554,409,303.0   3,384,448,151.0  -3,042,114,307.0
3       27,763,750.0     164,261,162.0     113,732,082.0     171,266,604.0
4      139,381,190.0     229,908,445.0      68,098,224.0     194,675,661.0
..               ...               ...               ...               ...
87     -43,417,500.0   8,241,585,034.0              None               nan
88    -985,849,423.0   1,567,953,217.0   8,589,609,985.0   2,081,571,341.0
89   5,815,263,717.0   3,589,220,796.0   3,589,220,796.0   1,165,303,369.0
90  -2,956,389,183.0     658,089,704.0      -2,149,597.0     342,346,086.0
91   1,873,070,192.0   5,815,263,717.0  12,176,681,184.0   3,589,220,796.0

   20130101-20131231
           (연결재무제표,)
0   -4,640,933,901.0
1   -5,799,164,183.0
2    1,585,260,973.0
3      142,661,638.0
4      186,423,806.0
..               ...
87               nan
88    -267,804,733.0
89     353,651,145.0
90   1,079,456,957.0
91   1,165,303,369.0

[92 rows x 12 columns]

In [184]:
df_cf.to_csv('data/현금흐름표.csv', index = False)