In [8]:
import datetime

In [9]:
data_li = pd.read_csv("data/상장폐지현황_.csv", encoding = 'CP949')
data_li.head(3)

,번호,회사명,종목코드,폐지일자,폐지사유,비고
0,1272,바이오빌,65940,2020-07-31,감사의견 거절(감사범위 제한 및 계속기업 존속능력에 대한 불확실성),NaN
1,1271,이엔드디,101360,2020-07-30,코스닥시장 이전상장,이엔드디
2,1270,한국제6호스팩,281410,2020-07-27,상장예비심사 청구서 미제출로 관리종목 지정 후 1개월 이내 동 사유 미해소,NaN

In [10]:
data_lis = data_li.loc[data_li['폐지사유'].str.contains('부도')]
data_list = data_lis.iloc[:,[1,3]]
data_list.head(3)

       회사명        폐지일자
50    데코앤이  2019-11-20
82      신텍  2018-07-09
119  금오하이텍  2017-06-07

In [11]:
data_list['폐지일자'] = data_list['폐지일자'].str.replace('-','')
data_list = data_list.reset_index(drop = True)
data_list.columns = ['company', 'date']
print(data_list.shape)
data_list.head(3)

/home/sk-j/anaconda3/envs/tf2/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

(70, 2)

  company      date
0    데코앤이  20191120
1      신텍  20180709
2   금오하이텍  20170607

In [12]:
com_df = pd.read_csv('data/bankrup_list.csv')
print(com_df.shape)
com_df.head(3)

(439, 2)

                     company      date
0  (유)동해건업                    20190403
1    (유)부강산업개발                20181017
2    (유)세일디앤아이                20190110

In [13]:
com_list = pd.concat([data_list, com_df])
com_list.reset_index(drop = True)
com_list['company'] = com_list['company'].str.replace(" ", "")
print(com_list.shape)
com_list.head(3)

(509, 2)

  company      date
0    데코앤이  20191120
1      신텍  20180709
2   금오하이텍  20170607

In [14]:
com_list

        company      date
0          데코앤이  20191120
1            신텍  20180709
2         금오하이텍  20170607
3        에이치앤아이  20160714
4         티에스엠텍  20150520
..          ...       ...
434  홍익엔지니어링(주)  20190402
435     홍주실업(주)  20181024
436     화신산업(주)  20191126
437   효진종합건설(주)  20181204
438        JS무역  20180907

[509 rows x 2 columns]

In [15]:
com_list['date'] = com_list['date'].astype(str)

In [16]:
com_list['date'].str[0:4].value_counts()

2019    318
2018    123
2004     10
2002      8
2003      8
2005      8
2010      7
2000      7
2012      5
1999      4
2009      2
2008      2
2015      2
2017      1
2011      1
2006      1
2001      1
2016      1
Name: date, dtype: int64

In [161]:
com_list.to_csv('data/com_list.csv', index = False)

In [17]:
len(com_list['company'])

509

In [18]:
have_list = []
no_list = []
for li in com_list['company']:
    try:
        basic_info = crp_list.find_by_corp_name(li, exactly=True)[0]
        have_list.append(li)
    except:
        no_list.append(li)

In [19]:
print(len(have_list))
have_list

55

['데코앤이',
 '신텍',
 '금오하이텍',
 '에이치앤아이',
 '티에스엠텍',
 '우양에이치씨',
 '배명금속',
 '금강제강',
 '풍림산업',
 '미주제강',
 '제이콤',
 '인네트',
 '신세계톰보이',
 '에스피코프',
 '쌈지',
 '카라반케이디이',
 '유리이에스',
 '아이비진',
 '우영',
 '알루코',
 '케이티씨텔레콤',
 '아이텍스필',
 '현주컴퓨터',
 '넥스텔',
 '지에스엔텍',
 '현대멀티캡',
 '중앙제지',
 '테크메이트',
 '텔슨전자',
 '금강화섬',
 '호성',
 '대호',
 '모닷텔',
 '화림모드',
 '서통',
 '계몽사',
 '코리아링크',
 '시스컴',
 '정산애강',
 '소프트윈',
 '심스밸리',
 '코닉스',
 '유니씨앤티',
 '아이씨켐',
 '디지텔',
 '삼한콘트롤스',
 '피어리스',
 '정일이엔씨',
 '삼산',
 '교하산업',
 '아진산업',
 '주화산업',
 '라인건설',
 '대륭산업',
 '한국종합철관']

In [20]:
print(len(no_list))
no_list

454

['SSCP',
 '하이드로젠파워',
 '케이씨오에너지',
 'GK파워',
 'VK',
 '영창악기제조',
 '동아정기',
 '대흥멀티통신',
 'KNC',
 '다산씨앤아이',
 '이론테크',
 '화인썬트로닉스',
 '대한종금',
 '한국대아진공',
 '영성제강',
 '(유)동해건업',
 '(유)부강산업개발',
 '(유)세일디앤아이',
 '(유)장수',
 '(의)서구의료재단여수성심병원',
 '(의)성실의료재단창녕요양병원',
 '(의)원의료재단동김해병원',
 '(주)ENS',
 '(주)JBM',
 '(주)거성합판목재',
 '(주)거연',
 '(주)거진상역',
 '(주)건형설비',
 '(주)경상엔지니어링',
 '(주)경안전선',
 '(주)경은',
 '(주)경천에스앤디',
 '(주)계진푸드',
 '(주)고려이알피',
 '(주)고려전기상사',
 '(주)관동물산',
 '(주)광명인치코리아',
 '(주)광진엔지니어링',
 '(주)광진종합물류',
 '(주)그린라이트',
 '(주)그린비',
 '(주)그린위드',
 '(주)그린플러스',
 '(주)글로벌리더스',
 '(주)금강골재',
 '(주)금빛식자재마트',
 '(주)금상종합주류',
 '(주)길상유통',
 '(주)나무와사람들',
 '(주)나우물산',
 '(주)나우상사',
 '(주)남윤산업',
 '(주)네오센스',
 '(주)뉴골드마인',
 '(주)뉴한일산업',
 '(주)님프만',
 '(주)다스코리아',
 '(주)다영산업개발',
 '(주)대건내츄럴',
 '(주)대건에프앤비',
 '(주)대경공영',
 '(주)대도건영',
 '(주)대림종합건설',
 '(주)대산씨에스에이',
 '(주)대상이엔지',
 '(주)대성',
 '(주)대양인터네셔널',
 '(주)대정설비',
 '(주)대진인더스트리',
 '(주)대한동력케이블',
 '(주)대한티앤피',
 '(주)대현산업',
 '(주)대화연료펌프',
 '(주)더에스앤에이치',
 '(주)더좋은푸드',
 '(주)더플랜',
 '(주)덕양상사',
 '(주)덕유',
 '(주)데코앤이',
 '(주)동경',
 '(주)동광오알티',
 '(주)동보철강',
 '(주)동성',
 '(주)동양프라텍',
 '(주)동영씨푸트',
 '(주)동오성',
 '(주)동오프랜지',
 '(주)동일월드',
 '(주)동진약품',
 '(주)동진주공',
 '(주)두리성',
 '(주)두산해운',
 '(주)디에스팩',
 '(주)디에이치메탈',
 '(주)디엠케이',
 '(주)디자인인터',
 '(주)뜨레비디엔씨',
 '(주)라이브론',
 '(주)라이트제림',
 '(주)로얄마트',
 '(주)마스타인터내셔날',
 '(주)마스타텍',
 '(주)마이웨이',
 '(주)마하',
 '(주)매일통상',
 '(주)명진농축산',
 '(주)명진종합건설',
 '(주)모터월드',
 '(주)모티브',
 '(주)미가',
 '(주)미건의료기',
 '(주)미건이엔씨',
 '(주)미드림',
 '(주)미르산업개발',
 '(주)미르전기',
 '(주)바쁜손유통',
 '(주)바우주택건설',
 '(주)반도케미칼',
 '(주)범진종합건설',
 '(주)베가',
 '(주)베델',
 '(주)보성해우소',
 '(주)부광종합건설',
 '(주)부흥산업',
 '(주)비젼케이엔에스',
 '(주)빠라베에사',
 '(주)삼부산업',
 '(주)삼성에이치앤비',
 '(주)삼우네오텍',
 '(주)삼원이피에스',
 '(주)삼협정밀',
 '(주)상일실업',
 '(주)상지이엔지',
 '(주)새한폴리머',
 '(주)서린주택',
 '(주)서신엔지니어링',
 '(주)서원상사',
 '(주)서일엠이씨',
 '(주)서평종합건설',
 '(주)서해에스에프씨',
 '(주)석영',
 '(주)성도',
 '(주)성도이앤씨',
 '(주)성우씨앤에프',
 '(주)성원물산',
 '(주)성원철강',
 '(주)성일하이테크',
 '(주)성지아트',
 '(주)성진메탈테크',
 '(주)성진화학',
 '(주)성창기업',
 '(주)성토건설',
 '(주)세광정밀',
 '(주)세교하이텍',
 '(주)세림에코',
 '(주)세영통상',
 '(주)세원금속',
 '(주)세일섬유',
 '(주)세진씨엔비',
 '(주)세코',
 '(주)세한건설',
 '(주)소년한국일보',
 '(주)솔목',
 '(주)수진산업개발',
 '(주)수호전기',
 '(주)순수화장품',
 '(주)스틸앤맨',
 '(주)시스네트',
 '(주)신광대리석',
 '(주)신라바스',
 '(주)신성에프엔씨',
 '(주)신세명',
 '(주)신영기업',
 '(주)신우엘에스산업',
 '(주)신진',
 '(주)신천',
 '(주)신화씨.엔.지',
 '(주)쌍용영월산기',
 '(주)써니',
 '(주)썬케이',
 '(주)씨엔에스인터',
 '(주)아림지앤코',
 '(주)아산이엔씨',
 '(주)아이피티',
 '(주)아트참',
 '(주)알파에스엠코리아',
 '(주)양원산업',
 '(주)에스아이테크',
 '(주)에스에스종합물류',
 '(주)에스에스텍스타일',
 '(주)에스에이치(SH)',
 '(주)에이스팜',
 '(주)엔에이치티',
 '(주)엔이더블유미래로',
 '(주)엘루',
 '(주)엘큐코리아',
 '(주)엠플러스쇼핑',
 '(주)영수산유통',
 '(주)영신칼스토리',
 '(주)영정물산',
 '(주)영지피엠씨',
 '(주)영진교역',
 '(주)영창레포츠',
 '(주)오로라유통',
 '(주)오산농민마트',
 '(주)오에이치',
 '(주)올리앤올슨',
 '(주)용전',
 '(주)우농이엔지',
 '(주)우리종합',
 '(주)우성아이비',
 '(주)우정건설산업',
 '(주)우정기획',
 '(주)우주상사',
 '(주)울성상사',
 '(주)웅지이엔지',
 '(주)원파워',
 '(주)윈테코',
 '(주)유건',
 '(주)유동에프씨',
 '(주)유승상사',
 '(주)은성개발',
 '(주)을지',
 '(주)이동수에프엔지',
 '(주)이솔유통',
 '(주)이엔산업',
 '(주)이화실업',
 '(주)인성',
 '(주)인성에프앤피',
 '(주)인일산업',
 '(주)인플랜',
 '(주)일만물유통',
 '(주)일선상사',
 '(주)일성유통',
 '(주)일신마린써비스',
 '(주)일진호이스트크레인',
 '(주)재연상사',
 '(주)정명케이블',
 '(주)정안산업',
 '(주)정일개발',
 '(주)정일기업',
 '(주)정일산업',
 '(주)정한섬유',
 '(주)제이앤컴퍼니',
 '(주)제이앤피무역',
 '(주)제이에이치무역',
 '(주)제이엔테크',
 '(주)제이와이인송산업',
 '(주)조일마트',
 '(주)지가캡',
 '(주)지앤케이',
 '(주)지엔비',
 '(주)지향',
 '(주)진미산업',
 '(주)진산종합중기',
 '(주)참다운푸드',
 '(주)창영비앤비',
 '(주)창원자동차학원',
 '(주)챔피온',
 '(주)첨단부품',
 '(주)청솔식품',
 '(주)청정에드원',
 '(주)초록이노텍',
 '(주)초록푸드시스템',
 '(주)충언건영',
 '(주)커먼컴',
 '(주)케이비현앤장',
 '(주)코리아산업',
 '(주)코빅건설',
 '(주)코지',
 '(주)코튼코리아',
 '(주)크린랩라텍스',
 '(주)타임스포츠',
 '(주)탐라',
 '(주)태성건설',
 '(주)태승섬유',
 '(주)태양그로윙',
 '(주)태우테크',
 '(주)태정아이엔디',
 '(주)태천',
 '(주)태화석재',
 '(주)태화화스너',
 '(주)테이크씨',
 '(주)통일목재',
 '(주)티엠코리아',
 '(주)티케이씨',
 '(주)퍼펙트마케팅',
 '(주)평산유통',
 '(주)풍산디에스',
 '(주)플러스디자인',
 '(주)플러스인테리어디자인',
 '(주)피알',
 '(주)피플엠',
 '(주)필아테크',
 '(주)하나마트',
 '(주)하이스코',
 '(주)하이테크노쎌',
 '(주)하이파오피스',
 '(주)학표벽지',
 '(주)한건티엔씨',
 '(주)한국세륜기',
 '(주)한라엠케이산업',
 '(주)한백에프앤씨',
 '(주)한양전선',
 '(주)한일세미컴',
 '(주)한일의료기',
 '(주)한일전기',
 '(주)해피로이앤씨',
 '(주)핸즈이노베이션',
 '(주)현경이엔씨',
 '(주)현대산기',
 '(주)현대유리',
 '(주)현대패널',
 '(주)호산세라믹스',
 '(주)화산',
 '(주)화성스틸판넬',
 '(주)화신산업',
 '(주)화인토일리트리',
 '(주)화제신문',
 '(주)황성산업',
 '(주)흥해종합건설',
 '(주)흥화',
 '<주>한미프렉시블',
 'HHICPHILKOREA주식회사',
 '강일약품(주)',
 '거원산업(주)',
 '건양개발주식회사',
 '국도골재(합자)',
 '굿모닝기룡건설(주)',
 '극동택시(주)',
 '금아기전(주)',
 '금정제십이차(주)',
 '금호기술(주)',
 '기영엔지니어링<주>',
 '기영항업(주)',
 '나인주택건설(주)',
 '농업법인(주)더부러',
 '농업회사법인(유)미',
 '농업회사법인(주)건농',
 '농업회사법인(주)대용축산',
 '농업회사법인(주)보금',
 '농업회사법인(주)지천글로벌',
 '농업회사법인(주)청풍미트',
 '농업회사법인킹스테이블(주)',
 '대경안전유리(주)',
 '대덕이엔씨(주)',
 '대동커튼월(주)',
 '대명산업(주)',
 '대선건설(주)',
 '대성전력(주)',
 '대아정공(주)',
 '대양영농조합',
 '대양주류(유)',
 '대영종합건설(주)',
 '대유중공업(주)',
 '대유플랜트(주)',
 '대은주류(주)',
 '대익건설(주)',
 '대한강재(주)',
 '대화공영(주)',
 '덕수철강(주)',
 '도량기업(주)',
 '동명건설(주)',
 '동북건설<주>',
 '동신수산(주)',
 '동아화이어테크(주)',
 '디엑스스퀘어드(주)',
 '라인씨스템(주)',
 '명성약품(주)',
 '미다스(주)',
 '미래공조플랜트(주)',
 '미래실업(주)',
 '미래파트너스(주)',
 '미소건설(주)',
 '배성물산(주)',
 '부광엔지니어링(주)',
 '부울경산업(주)',
 '비엠글로벌(주)',
 '상보건설(주)',
 '서진설비(주)',
 '서현스틸(주)',
 '석달(주)',
 '선우산업(주)',
 '성명산업(유)',
 '세원건설(주)',
 '세원목재(주)',
 '세존상사(주)',
 '신평유기(주)',
 '신흥설비(주)',
 '아강테크(주)',
 '아이타올(주)',
 '안동석건(주)',
 '안동석재산업(주)',
 '에스에이에스(주)',
 '에스에이치엠(주)',
 '에이티아이유통(주)',
 '엠앤에스산업(주)',
 '엠에이치건설(주)',
 '영지산업(주)',
 '영창건업(주)',
 '와일드마운틴(주)',
 '용마철강(주)',
 '우리이엔씨(주)',
 '우주소방전기(주)',
 '우진중공업(주)',
 '위더스앤플랜(주)',
 '위캔글로벌(주)',
 '유복전기(주)',
 '유승종합건설(주)',
 '율원약품(주)',
 '의료법인성석의료재단',
 '의료법인애민의료재단',
 '이선케이블(주)',
 '이오제이이앤씨(주)',
 '일성전장(주)',
 '재영실업(주)',
 '정석건업(주)',
 '제이알철강(주)',
 '제이엠유통(주)',
 '주)태백광업',
 '지웅전기(주)',
 '진우창호(주)',
 '철인종합건설(주)',
 '청솔아이엔에스(주)',
 '칼텍(주)',
 '케이디데니스패션(주)',
 '케이씨피(주)',
 '케이아이유통(주)',
 '케이엠에프(주)',
 '코리아팜(주)',
 '탐라도서(주)',
 '태경산업개발(주)',
 '토고(주)',
 '통일경제(주)',
 '통일운수(합자)',
 '피알캠(주)',
 '하이코건설(주)',
 '한겨레건설(주)',
 '한국마그넷(주)',
 '한국메디케어(주)',
 '한독건설(주)',
 '한성기업<주>',
 '한성약품(주)',
 '한성엔지니어링(주)',
 '한아종합기술(주)',
 '한영콘트롤(주)',
 '한일엠이써비스(주)',
 '한일전설(주)',
 '호산이엔지(주)',
 '홍익엔지니어링(주)',
 '홍주실업(주)',
 '화신산업(주)',
 '효진종합건설(주)',
 'JS무역']

In [21]:
print('부도기업:', len(com_list))
print('조회가능 기업:',len(have_list))
print('조회불가 기업:',len(no_list))

부도기업: 509
조회가능 기업: 55
조회불가 기업: 454

In [26]:
h_list = pd.DataFrame(have_list, columns = ['name'])
print(len(h_list))
h_list.head()

55

     name
0    데코앤이
1      신텍
2   금오하이텍
3  에이치앤아이
4   티에스엠텍

In [24]:
h_list.to_csv('data/c_list.csv', index = False)

In [25]:
pd.read_csv('data/c_list.csv')

       name
0      데코앤이
1        신텍
2     금오하이텍
3    에이치앤아이
4     티에스엠텍
5    우양에이치씨
6      배명금속
7      금강제강
8      풍림산업
9      미주제강
10      제이콤
11      인네트
12   신세계톰보이
13    에스피코프
14       쌈지
15  카라반케이디이
16    유리이에스
17     아이비진
18       우영
19      알루코
20  케이티씨텔레콤
21    아이텍스필
22    현주컴퓨터
23      넥스텔
24    지에스엔텍
25    현대멀티캡
26     중앙제지
27    테크메이트
28     텔슨전자
29     금강화섬
30       호성
31       대호
32      모닷텔
33     화림모드
34       서통
35      계몽사
36    코리아링크
37      시스컴
38     정산애강
39     소프트윈
40     심스밸리
41      코닉스
42    유니씨앤티
43     아이씨켐
44      디지텔
45   삼한콘트롤스
46     피어리스
47    정일이엔씨
48       삼산
49     교하산업
50     아진산업
51     주화산업
52     라인건설
53     대륭산업
54   한국종합철관

In [1]:
import dart_fss as dart
import pandas as pd

In [2]:
api_key='7bba91f51399cd6256c184c5ad0b2539c0bfd8b6'
dart.set_api_key(api_key=api_key)

'7bba91f51399cd6256c184c5ad0b2539c0bfd8b6'

In [3]:
crp_list = dart.get_corp_list()

Output()

Output()

Output()

In [4]:
len(crp_list.find_by_product(product = '제조', market = 'K'))

84

In [5]:
basic_info = crp_list.find_by_corp_name('이매진아시아', exactly=True)[0]

In [6]:
fs = basic_info.extract_fs(bgn_de='20190101')

Output()

Output()

HBox(children=(FloatProgress(value=0.0, description='Annual reports', max=1.0, style=ProgressStyle(description…

In [7]:
# 'bs' 재무상태표, 'is' 손익계산서, 'cis' 포괄손익계산서, 'cf' 현금흐름표
df_cis = fs['cis']
df_bs = fs['bs']
df_cf = fs['cf']

In [22]:
df_cis.to_csv('data/포괄손익계산서.csv', index = False)

In [15]:
df_cis.shape

(35, 10)

In [16]:
df_cis.head(5)

  [D431410] Statement of comprehensive income, by function of expense - Consolidated financial statements (Unit: KRW)  \
                                                                                                           concept_id
0                                  ifrs-full_Revenue
1                              ifrs-full_CostOfSales
2                              ifrs-full_GrossProfit
3     dart_TotalSellingGeneralAdministrativeExpenses
4                           dart_OperatingIncomeLoss

                                                                          \
   label_ko                                 label_en              class0
0       매출액                           Revenue(Sales)  포괄손익계산서 [abstract]
1      매출원가                            Cost of sales  포괄손익계산서 [abstract]
2     매출총이익                             Gross profit  포괄손익계산서 [abstract]
3   판매비와관리비  Selling general administrative expenses  포괄손익계산서 [abstract]
4  영업이익(손실)                   Operating income(loss)  포괄손익계산서 [abstract]

                          20190101-20191231 20180101-20181231  \
     class1 class2 class3         (연결재무제표,)         (연결재무제표,)
0       매출액   None   None  12,690,903,987.0  26,187,470,807.0
1      매출원가   None   None  12,607,067,912.0  24,916,951,370.0
2     매출총이익   None   None      83,836,075.0   1,270,519,437.0
3   판매비와관리비   None   None   3,863,460,724.0   5,214,421,708.0
4  영업이익(손실)   None   None  -3,779,624,649.0  -3,943,902,271.0

  20170101-20171231
          (연결재무제표,)
0  14,262,299,673.0
1  15,083,677,830.0
2    -821,378,157.0
3   6,019,047,667.0
4  -6,840,425,824.0

In [17]:
df_cis_1 = df_cis.iloc[:,[1,7,8,9]]
df_cis_1.head(5)

,"[D431410] Statement of comprehensive income, by function of expense - Consolidated financial statements (Unit: KRW)",20190101-20191231,20180101-20181231,20170101-20171231
,label_ko,"(연결재무제표,)","(연결재무제표,)","(연결재무제표,)"
0,매출액,"12,690,903,987.0","26,187,470,807.0","14,262,299,673.0"
1,매출원가,"12,607,067,912.0","24,916,951,370.0","15,083,677,830.0"
2,매출총이익,"83,836,075.0","1,270,519,437.0","-821,378,157.0"
3,판매비와관리비,"3,863,460,724.0","5,214,421,708.0","6,019,047,667.0"
4,영업이익(손실),"-3,779,624,649.0","-3,943,902,271.0","-6,840,425,824.0"

In [18]:
df_cis_1.columns

MultiIndex([('[D431410] Statement of comprehensive income, by function of expense - Consolidated financial statements (Unit: KRW)', ...),
            (                                                                                                  '20190101-20191231', ...),
            (                                                                                                  '20180101-20181231', ...),
            (                                                                                                  '20170101-20171231', ...)],
           )

In [19]:
df_cis_1 = df_cis.iloc[:,[1,7,8,9]]
df_cis_1.columns = ['', df_cis_1.columns[1][0], df_cis_1.columns[2][0], df_cis_1.columns[3][0]]
df_cis_1 = df_cis_1.T
df_cis_1 = df_cis_1.rename(columns=df_cis_1.iloc[0])
df_cis_1 = df_cis_1.drop(df_cis_1.index[0])
df_cis_1 = df_cis_1.reset_index().rename(columns={'index':'date'})
df_cis_1['date'] = df_cis_1['date'].str[9:]
print(df_cis_1.shape)
df_cis_1.head()

(3, 36)

,date,매출액,매출원가,매출총이익,판매비와관리비,영업이익(손실),영업외수익,금융수익,종속기업및관계기업이익,기타수익,...,계속영업당기순손익,중단영업당기순손익,지배기업소유주지분,비지배지분,기본주당이익(손실),계속영업기본주당손익,중단영업기본주당손익,희석주당이익(손실),계속영업희석주당손익,중단영업기본주당손익
0,20191231,"12,690,903,987.0","12,607,067,912.0","83,836,075.0","3,863,460,724.0","-3,779,624,649.0","3,976,742,997.0","1,204,645,697.0","2,401,030,418.0","371,066,882.0",...,"-560,582,235.0",0.0,"-19,285,731,302.0","-560,582,235.0",-519.0,-519.0,0.0,-519.0,-519.0,0.0
1,20181231,"26,187,470,807.0","24,916,951,370.0","1,270,519,437.0","5,214,421,708.0","-3,943,902,271.0","1,116,468,403.0","738,307,926.0","11,044,142.0","367,116,335.0",...,"-29,011,391.0","255,588,326.0","-11,827,379,111.0","226,576,935.0",-333.0,-134.0,-199.0,-333.0,-134.0,-199.0
2,20171231,"14,262,299,673.0","15,083,677,830.0","-821,378,157.0","6,019,047,667.0","-6,840,425,824.0","2,140,222,096.0","1,249,748,914.0","750,398,099.0","140,075,083.0",...,"-127,129,059.0","150,762,095.0","-16,349,813,866.0","23,633,036.0",-499.0,-310.0,-189.0,-499.0,-310.0,-189.0

In [35]:
df_cis_1.astype(object)

,date,매출액,매출원가,매출총이익,판매비와관리비,영업이익(손실),영업외수익,금융수익,종속기업및관계기업이익,기타수익,...,계속영업당기순손익,중단영업당기순손익,지배기업소유주지분,비지배지분,기본주당이익(손실),계속영업기본주당손익,중단영업기본주당손익,희석주당이익(손실),계속영업희석주당손익,중단영업기본주당손익
0,20191231,"12,690,903,987.0","12,607,067,912.0","83,836,075.0","3,863,460,724.0","-3,779,624,649.0","3,976,742,997.0","1,204,645,697.0","2,401,030,418.0","371,066,882.0",...,"-560,582,235.0",0.0,"-19,285,731,302.0","-560,582,235.0",-519.0,-519.0,0.0,-519.0,-519.0,0.0
1,20181231,"26,187,470,807.0","24,916,951,370.0","1,270,519,437.0","5,214,421,708.0","-3,943,902,271.0","1,116,468,403.0","738,307,926.0","11,044,142.0","367,116,335.0",...,"-29,011,391.0","255,588,326.0","-11,827,379,111.0","226,576,935.0",-333.0,-134.0,-199.0,-333.0,-134.0,-199.0
2,20171231,"14,262,299,673.0","15,083,677,830.0","-821,378,157.0","6,019,047,667.0","-6,840,425,824.0","2,140,222,096.0","1,249,748,914.0","750,398,099.0","140,075,083.0",...,"-127,129,059.0","150,762,095.0","-16,349,813,866.0","23,633,036.0",-499.0,-310.0,-189.0,-499.0,-310.0,-189.0

In [44]:
df_cis_2 = df_cis_1.iloc[:,1:36]
df_cis_2

,매출액,매출원가,매출총이익,판매비와관리비,영업이익(손실),영업외수익,금융수익,종속기업및관계기업이익,기타수익,영업외비용,...,계속영업당기순손익,중단영업당기순손익,지배기업소유주지분,비지배지분,기본주당이익(손실),계속영업기본주당손익,중단영업기본주당손익,희석주당이익(손실),계속영업희석주당손익,중단영업기본주당손익
0,"12,690,903,987.0","12,607,067,912.0","83,836,075.0","3,863,460,724.0","-3,779,624,649.0","3,976,742,997.0","1,204,645,697.0","2,401,030,418.0","371,066,882.0","20,043,431,885.0",...,"-560,582,235.0",0.0,"-19,285,731,302.0","-560,582,235.0",-519.0,-519.0,0.0,-519.0,-519.0,0.0
1,"26,187,470,807.0","24,916,951,370.0","1,270,519,437.0","5,214,421,708.0","-3,943,902,271.0","1,116,468,403.0","738,307,926.0","11,044,142.0","367,116,335.0","1,955,788,161.0",...,"-29,011,391.0","255,588,326.0","-11,827,379,111.0","226,576,935.0",-333.0,-134.0,-199.0,-333.0,-134.0,-199.0
2,"14,262,299,673.0","15,083,677,830.0","-821,378,157.0","6,019,047,667.0","-6,840,425,824.0","2,140,222,096.0","1,249,748,914.0","750,398,099.0","140,075,083.0","4,789,303,628.0",...,"-127,129,059.0","150,762,095.0","-16,349,813,866.0","23,633,036.0",-499.0,-310.0,-189.0,-499.0,-310.0,-189.0

In [25]:
import string

In [46]:
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [13]:
import numpy as np

In [14]:
var_1_dic = {'자본총계': 4, '자산총계': 4, '매입채무': 11, '매출채권': 11,
             '부채총계': 4, '유동부채': 4, '유동자산': 4, '재고자산': 4, 'company': 7}
var_2_dic = {'date':4, '매출총이익': 5, '법인세비용차감': 15, '당기순이익': 10,
             'company': 7}

In [17]:
cis_a = pd.DataFrame(columns=['date', '매출총이익', '법인세비용차감전순이익',
                            '당기순이익'])
cis_b = pd.DataFrame(columns=['date', '매출총이익', '법인세비용차감전순이익',
                            '당기순이익'])
cis_a

Empty DataFrame
Columns: [date, 매출총이익, 법인세비용차감전순이익, 당기순이익]
Index: []

In [20]:
count = 0
for var2, var2_ in var_2_dic.items():
    for cis in df_cis_1.columns:
        if var2 in cis:
            if var2_ >= len(cis):
                cis_a.iloc[:,count] = df_cis_1[cis]
                count += 1
                print(cis)
cis_b = pd.concat([cis_b, cis_a])

date
매출총이익
법인세비용차감전순이익(손실)
당기순이익(손실)

In [21]:
cis_b

       date           매출총이익       법인세비용차감전순이익             당기순이익
0  20191231    83,836,075.0 -19,846,313,537.0 -19,846,313,537.0
1  20181231 1,270,519,437.0  -4,783,222,029.0 -11,600,802,176.0
2  20171231  -821,378,157.0  -9,489,507,356.0 -15,088,717,271.0

In [112]:
cis

'date'

In [74]:
aa

['date', 'date', '매출총이익', '법인세비용차감전순이익(손실)', '당기순이익(손실)']

In [75]:
df_cis_1[aa]

       date      date           매출총이익   법인세비용차감전순이익(손실)         당기순이익(손실)
0  20191231  20191231    83,836,075.0 -19,846,313,537.0 -19,846,313,537.0
1  20181231  20181231 1,270,519,437.0  -4,783,222,029.0 -11,600,802,176.0
2  20171231  20171231  -821,378,157.0  -9,489,507,356.0 -15,088,717,271.0

In [25]:
df_bs

   [D220000] Statement of financial position, order of liquidity - Consolidated financial statements (Unit: KRW)  \
                                                                                                      concept_id
0                    ifrs-full_CashAndCashEquivalents
1   dart_ShortTermDepositsNotClassifiedAsCashEquiv...
2           ifrs-full_TradeAndOtherCurrentReceivables
3                          ifrs-full_CurrentTaxAssets
4                               ifrs-full_Inventories
5                             dart_OtherCurrentAssets
6   dart_LongTermDepositsNotClassifiedAsCashEquiva...
7   dart_LongTermTradeAndOtherNonCurrentReceivable...
8                 ifrs-full_PropertyPlantAndEquipment
9         ifrs-full_IntangibleAssetsOtherThanGoodwill
10                                 dart_GoodwillGross
11  ifrs-full_InvestmentsInSubsidiariesJointVentur...
12                         dart_OtherNonCurrentAssets
13                                   ifrs-full_Assets
14             ifrs-full_TradeAndOtherCurrentPayables
15  entity00122339_udf_BS_2017121419281203_Liabili...
16                    ifrs-full_CurrentTaxLiabilities
17                       dart_OtherCurrentLiabilities
18       dart_LongTermTradeAndOtherNonCurrentPayables
19  entity00122339_udf_BS_20171214192918842_Liabil...
20                   ifrs-full_DeferredTaxLiabilities
21                              ifrs-full_Liabilities
22       ifrs-full_EquityAttributableToOwnersOfParent
23                            ifrs-full_IssuedCapital
24                                dart_CapitalSurplus
25             dart_ElementsOfOtherStockholdersEquity
26  dart_OtherComprehensiveIncomeLossAccumulatedAm...
27                         ifrs-full_RetainedEarnings
28                  ifrs-full_NoncontrollingInterests
29                                   ifrs-full_Equity
30                     ifrs-full_EquityAndLiabilities

                                                                            \
               label_ko                                           label_en
0              현금및현금성자산                          Cash and cash equivalents
1                단기금융자산  Short-term deposits not classified as cash equ...
2           매출채권 및 기타채권                Trade and other current receivables
3               당기법인세자산                                 Current tax assets
4                  재고자산                                        Inventories
5                기타유동자산                               Other current assets
6                장기금융자산  Long-term deposits not classified as cash equi...
7         장기매출채권 및 기타채권  Long-term trade and other non-current receivab...
8                  유형자산                      Property, plant and equipment
9                  무형자산              Intangible assets other than goodwill
10                  영업권                                    Goodwill, gross
11     종속기업 및 관계기업 투자자산  Investments in subsidiaries, joint ventures an...
12              기타비유동자산                           Other non-current assets
13                 자산총계                                       Total assets
14          매입채무 및 기타채무                   Trade and other current payables
15               단기금융부채                                         Borrowings
16              당기법인세부채                            Current tax liabilities
17               기타유동부채                          Other current liabilities
18     장기매입채무 및 기타비유동채무     Long-term trade and other non-current payables
19               장기금융부채                    Long-term financial liabilities
20              이연법인세부채                           Deferred tax liabilities
21                 부채총계                                  Total liabilities
22  지배기업의 소유주에게 귀속되는 자본            Equity attributable to owners of parent
23                  자본금                                     Issued capital
24                자본잉여금                                    Capital surplus
25                 자본조정             Elements of other stockholder's equity
26            기타포괄손익누계액  Other Comprehensive income/loss accumulated am...
27           이익잉여금(결손금)                                  Retained earnings
28                비지배지분                          Non-controlling interests
29                 자본총계                                       Total equity
30              자본과부채총계                       Total equity and liabilities

                                                                      \
              class0         class1               class2      class3
0   재무상태표 [abstract]  자산 [abstract]             현금및현금성자산        None
1   재무상태표 [abstract]  자산 [abstract]               단기금융자산        None
2   재무상태표 [abstract]  자산 [abstract]          매출채권 및 기타채권        None
3   재무상태표 [abstract]  자산 [abstract]              당기법인세자산        None
4   재무상태표 [abstract]  자산 [abstract]                 재고자산        None
5   재무상태표 [abstract]  자산 [abstract]               기타유동자산        None
6   재무상태표 [abstract]  자산 [abstract]               장기금융자산        None
7   재무상태표 [abstract]  자산 [abstract]        장기매출채권 및 기타채권        None
8   재무상태표 [abstract]  자산 [abstract]                 유형자산        None
9   재무상태표 [abstract]  자산 [abstract]                 무형자산        None
10  재무상태표 [abstract]  자산 [abstract]                  영업권        None
11  재무상태표 [abstract]  자산 [abstract]     종속기업 및 관계기업 투자자산        None
12  재무상태표 [abstract]  자산 [abstract]              기타비유동자산        None
13  재무상태표 [abstract]  자산 [abstract]                 자산총계        None
14  재무상태표 [abstract]  부채 [abstract]          매입채무 및 기타채무        None
15  재무상태표 [abstract]  부채 [abstract]               단기금융부채        None
16  재무상태표 [abstract]  부채 [abstract]              당기법인세부채        None
17  재무상태표 [abstract]  부채 [abstract]               기타유동부채        None
18  재무상태표 [abstract]  부채 [abstract]     장기매입채무 및 기타비유동채무        None
19  재무상태표 [abstract]  부채 [abstract]               장기금융부채        None
20  재무상태표 [abstract]  부채 [abstract]              이연법인세부채        None
21  재무상태표 [abstract]  부채 [abstract]                 부채총계        None
22  재무상태표 [abstract]  자본 [abstract]  지배기업의 소유주에게 귀속되는 자본        None
23  재무상태표 [abstract]  자본 [abstract]  지배기업의 소유주에게 귀속되는 자본         자본금
24  재무상태표 [abstract]  자본 [abstract]  지배기업의 소유주에게 귀속되는 자본       자본잉여금
25  재무상태표 [abstract]  자본 [abstract]  지배기업의 소유주에게 귀속되는 자본        자본조정
26  재무상태표 [abstract]  자본 [abstract]  지배기업의 소유주에게 귀속되는 자본   기타포괄손익누계액
27  재무상태표 [abstract]  자본 [abstract]  지배기업의 소유주에게 귀속되는 자본  이익잉여금(결손금)
28  재무상태표 [abstract]  자본 [abstract]                비지배지분        None
29  재무상태표 [abstract]  자본 [abstract]                 자본총계        None
30  재무상태표 [abstract]        자본과부채총계                 None        None

            20191231          20181231          20171231
           (연결재무제표,)         (연결재무제표,)         (연결재무제표,)
0    3,224,106,992.0  10,034,226,743.0   1,226,320,070.0
1        2,000,000.0   1,173,092,000.0   1,450,236,786.0
2    6,781,828,352.0   5,075,492,062.0  14,047,298,184.0
3       12,588,250.0     102,346,424.0      29,436,810.0
4                0.0      60,000,000.0   2,081,462,454.0
5    3,238,970,733.0  12,531,380,266.0   2,500,083,696.0
6       10,000,000.0     497,910,700.0   6,421,352,167.0
7    3,342,666,897.0   1,682,910,000.0   1,030,170,000.0
8    1,239,179,431.0     416,162,603.0   7,523,468,706.0
9       73,588,502.0     356,756,953.0   1,802,302,393.0
10               nan               nan  14,523,415,716.0
11               0.0               0.0               nan
12               nan               nan   2,033,443,965.0
13  17,924,929,157.0  31,930,277,751.0  54,668,990,947.0
14   1,461,220,123.0   2,585,771,788.0   6,290,610,322.0
15   3,505,625,659.0   3,439,997,498.0   8,317,251,149.0
16               0.0       3,164,750.0     336,482,403.0
17     541,092,897.0     647,697,833.0     739,322,166.0
18               nan               nan      60,792,313.0
19     501,618,446.0               0.0     390,918,073.0
20               nan               nan     899,852,961.0
21   6,009,557,125.0   6,676,631,869.0  17,035,229,387.0
22  12,183,837,403.0  25,509,728,281.0  36,186,204,530.0
23  21,889,085,500.0  17,839,558,000.0  17,562,550,500.0
24  87,751,101,280.0  85,822,960,995.0  85,101,637,450.0
25     -26,640,400.0     -53,363,040.0     -53,363,040.0
26               nan               nan  -1,237,463,559.0
27 -97,429,708,977.0 -78,099,427,674.0 -65,187,156,821.0
28    -268,465,371.0    -256,082,399.0   1,447,557,030.0
29  11,915,372,032.0  25,253,645,882.0  37,633,761,560.0
30  17,924,929,157.0  31,930,277,751.0  54,668,990,947.0

In [183]:
df_bs.to_csv('data/재무상태표.csv', index = False)

In [27]:
df_bs_1 = df_bs.iloc[:,[1,7,8,9]]
df_bs_1.columns = ['', df_bs_1.columns[1][0], df_bs_1.columns[2][0], df_bs_1.columns[3][0]]
df_bs_1 = df_bs_1.T
df_bs_1 = df_bs_1.rename(columns=df_bs_1.iloc[0])
df_bs_1 = df_bs_1.drop(df_bs_1.index[0])
df_bs_1 = df_bs_1.reset_index().rename(columns={'index':'date'})
print(df_bs_1.shape)
df_bs_1.head()

(3, 32)

,date,현금및현금성자산,단기금융자산,매출채권 및 기타채권,당기법인세자산,재고자산,기타유동자산,장기금융자산,장기매출채권 및 기타채권,유형자산,...,부채총계,지배기업의 소유주에게 귀속되는 자본,자본금,자본잉여금,자본조정,기타포괄손익누계액,이익잉여금(결손금),비지배지분,자본총계,자본과부채총계
0,20191231,"3,224,106,992.0","2,000,000.0","6,781,828,352.0","12,588,250.0",0.0,"3,238,970,733.0","10,000,000.0","3,342,666,897.0","1,239,179,431.0",...,"6,009,557,125.0","12,183,837,403.0","21,889,085,500.0","87,751,101,280.0","-26,640,400.0",NaN,"-97,429,708,977.0","-268,465,371.0","11,915,372,032.0","17,924,929,157.0"
1,20181231,"10,034,226,743.0","1,173,092,000.0","5,075,492,062.0","102,346,424.0","60,000,000.0","12,531,380,266.0","497,910,700.0","1,682,910,000.0","416,162,603.0",...,"6,676,631,869.0","25,509,728,281.0","17,839,558,000.0","85,822,960,995.0","-53,363,040.0",NaN,"-78,099,427,674.0","-256,082,399.0","25,253,645,882.0","31,930,277,751.0"
2,20171231,"1,226,320,070.0","1,450,236,786.0","14,047,298,184.0","29,436,810.0","2,081,462,454.0","2,500,083,696.0","6,421,352,167.0","1,030,170,000.0","7,523,468,706.0",...,"17,035,229,387.0","36,186,204,530.0","17,562,550,500.0","85,101,637,450.0","-53,363,040.0","-1,237,463,559.0","-65,187,156,821.0","1,447,557,030.0","37,633,761,560.0","54,668,990,947.0"

In [57]:
for var1, var1_ in var_1_dic.items():
    for bs in df_bs_1.columns:
        if var1 in bs:
            if var1_ >= len(bs):
                print(bs)

자본총계
자산총계
매입채무 및 기타채무
매출채권 및 기타채권
부채총계
재고자산

In [173]:
df_cf

   [D520000] Statement of cash flows, indirect method - Consolidated financial statements (Unit: KRW)  \
                                                                                           concept_id
0    ifrs-full_CashFlowsFromUsedInOperatingActivities
1              dart_ProfitLossForStatementOfCashFlows
2         ifrs-full_AdjustmentsForReconcileProfitLoss
3   dart_AdjustmentsForAssetsLiabilitiesOfOperatin...
4   ifrs-full_InterestReceivedClassifiedAsOperatin...
5   ifrs-full_InterestPaidClassifiedAsOperatingAct...
6   ifrs-full_IncomeTaxesPaidRefundClassifiedAsOpe...
7    ifrs-full_CashFlowsFromUsedInInvestingActivities
8   dart_ProceedsFromSalesOfShortTermFinancialInst...
9                                dart_DecreaseInLoans
10  dart_ProceedsFromSalesOfAvailableForSaleFinanc...
11  ifrs-full_CashFlowsFromLosingControlOfSubsidia...
12  dart_ProceedsFromSalesOfInvestmentsInSubsidiaries
13  ifrs-full_CashReceiptsFromRepaymentOfAdvancesA...
14  ifrs-full_CashAdvancesAndLoansMadeToOtherParti...
15  dart_ProceedsFromSalesOfIntangibleAssetsUnderD...
16  ifrs-full_ProceedsFromSalesOfPropertyPlantAndE...
17                   dart_DecreaseInGuaranteeDeposits
18  dart_ProceedsFromSalesOfLongTermFinancialInstr...
19       dart_PurchaseOfShortTermFinancialInstruments
20                               dart_IncreaseInLoans
21  dart_PurchaseOfCurrentAvailableForSaleFinancia...
22  entity00122339_udf_CF_2019327105542607_CashFlo...
23    dart_PurchaseOfIntangibleAssetsUnderDevelopment
24        dart_PurchaseOfLongTermFinancialInstruments
25  ifrs-full_PurchaseOfPropertyPlantAndEquipmentC...
26               dart_PurchaseOfOtherIntangibleAssets
27  ifrs-full_PurchaseOfIntangibleAssetsClassified...
28                   dart_IncreaseInGuaranteeDeposits
29         dart_CashPaymentsForDiscontinuedOperations
30   ifrs-full_CashFlowsFromUsedInFinancingActivities
31               dart_ProceedsFromShortTermBorrowings
32  dart_ProceedsFromFinanceLeaseLiabilitiesClassi...
33                  dart_ProceedsFromConvertibleBonds
34                ifrs-full_ProceedsFromIssuingShares
35               dart_RepaymentsOfShortTermBorrowings
36  ifrs-full_PaymentsOfFinanceLeaseLiabilitiesCla...
37                  dart_RepaymentsOfConvertibleBonds
38                   dart_RepaymentsOfBondWithWarrant
39  ifrs-full_IncreaseDecreaseInCashAndCashEquival...
40   dart_CashAndCashEquivalentsAtBeginningOfPeriodCf
41         dart_CashAndCashEquivalentsAtEndOfPeriodCf

                                                                           \
              label_ko                                           label_en
0             영업활동현금흐름     Cash flows from (used in) operating activities
1            당기순이익(손실)                                      Profit (loss)
2       당기순이익조정을 위한 가감             Adjustments to reconcile profit (loss)
3     영업활동으로인한자산ㆍ부채의변동  Adjustments for assets and liabilities of oper...
4                 이자수취                                  Interest received
5                 이자지급                                      Interest paid
6            법인세환급(납부)                         Income taxes paid (refund)
7             투자활동현금흐름     Cash flows from (used in) investing activities
8            단기금융상품의감소  Proceeds from sales of short term Financial In...
9            단기대여금의 감소                                  Decrease in loans
10     당기손익공정가치측정자산의처분  Proceeds from sales of available-for-sale fina...
11  종속기업 취득에 따른 순 현금흐름  Cash flows from losing control of subsidiaries...
12  종속기업 처분에 따른 순 현금흐름  Proceeds from sales of investments in subsidia...
13        창투설립 선급금의 회수  Cash receipts from repayment of advances and l...
14             선급금의 증가      Cash advances and loans made to other parties
15         프로젝트투자자산의처분  Proceeds from sales of intangible assets under...
16            유형자산의 처분  Proceeds from sales of property, plant and equ...
17             보증금의 감소                     Decrease in guarantee deposits
18           장기금융상품의감소  Proceeds from sales of long-term financial ins...
19           단기금융삼품의증가       Purchase of short term Financial Instruments
20           단기대여금의 증가                                  Increase in loans
21          매도가능증권의 취득  Purchase of current available-for-sale financi...
22  당기손익-공정가치측정금융자산의취득            Purchase of fair value financial asset.
23        프로젝트투자자산의 취득    Purchase of intangible assets under development
24          장기금융상품의 증가        Purchase of long-term financial instruments
25            유형자산의 취득          Purchase of property, plant and equipment
26          기타무형자산의 취득                Purchase of other intangible assets
27            무형자산의 취득                      Purchase of intangible assets
28             보증금의 증가                     Increase in guarantee deposits
29      사업결합으로 인한 현금유출          Cash payments for discontinued operations
30            재무활동현금흐름     Cash flows from (used in) financing activities
31           단기차입금의 증가                Proceeds from short term borrowings
32          금융리스부채의 증가  Proceeds from finance lease liabilities classi...
33            전환사채의 증가                    Proceeds from convertible bonds
34                유상증자                       Proceeds from issuing shares
35           단기차입금의 상환                Repayments of short term borrowings
36           금융리스부채의상환              Payments of finance lease liabilities
37            전환사채의 감소                    Repayments of convertible bonds
38        신주인수권부사채의 상환                    Repayments of bond with warrant
39    현금및현금성자산의순증가(감소)  Net increase (decrease) in cash and cash equiv...
40          기초현금및현금성자산   Cash and cash equivalents at beginning of period
41          기말현금및현금성자산         Cash and cash equivalents at end of period

                                                           20190101-20191231  \
              class0            class1              class2         (연결재무제표,)
0   현금흐름표 [abstract]          영업활동현금흐름                None  -6,256,061,272.0
1   현금흐름표 [abstract]          영업활동현금흐름           당기순이익(손실) -19,846,313,537.0
2   현금흐름표 [abstract]          영업활동현금흐름      당기순이익조정을 위한 가감  16,482,969,417.0
3   현금흐름표 [abstract]          영업활동현금흐름    영업활동으로인한자산ㆍ부채의변동  -2,203,657,409.0
4   현금흐름표 [abstract]          영업활동현금흐름                이자수취      59,581,132.0
5   현금흐름표 [abstract]          영업활동현금흐름                이자지급     835,209,069.0
6   현금흐름표 [abstract]          영업활동현금흐름           법인세환급(납부)     -86,568,194.0
7   현금흐름표 [abstract]          투자활동현금흐름                None  -6,310,233,797.0
8   현금흐름표 [abstract]          투자활동현금흐름           단기금융상품의감소      12,000,000.0
9   현금흐름표 [abstract]          투자활동현금흐름           단기대여금의 감소   6,228,547,601.0
10  현금흐름표 [abstract]          투자활동현금흐름     당기손익공정가치측정자산의처분               0.0
11  현금흐름표 [abstract]          투자활동현금흐름  종속기업 취득에 따른 순 현금흐름   2,010,000,000.0
12  현금흐름표 [abstract]          투자활동현금흐름  종속기업 처분에 따른 순 현금흐름     661,374,178.0
13  현금흐름표 [abstract]          투자활동현금흐름        창투설립 선급금의 회수   6,000,000,000.0
14  현금흐름표 [abstract]          투자활동현금흐름             선급금의 증가               nan
15  현금흐름표 [abstract]          투자활동현금흐름         프로젝트투자자산의처분      52,842,620.0
16  현금흐름표 [abstract]          투자활동현금흐름            유형자산의 처분     394,853,983.0
17  현금흐름표 [abstract]          투자활동현금흐름             보증금의 감소  11,598,724,000.0
18  현금흐름표 [abstract]          투자활동현금흐름           장기금융상품의감소               0.0
19  현금흐름표 [abstract]          투자활동현금흐름           단기금융삼품의증가      12,000,000.0
20  현금흐름표 [abstract]          투자활동현금흐름           단기대여금의 증가   7,971,058,660.0
21  현금흐름표 [abstract]          투자활동현금흐름          매도가능증권의 취득               nan
22  현금흐름표 [abstract]          투자활동현금흐름  당기손익-공정가치측정금융자산의취득  10,199,998,500.0
23  현금흐름표 [abstract]          투자활동현금흐름        프로젝트투자자산의 취득               nan
24  현금흐름표 [abstract]          투자활동현금흐름          장기금융상품의 증가               0.0
25  현금흐름표 [abstract]          투자활동현금흐름            유형자산의 취득     436,047,019.0
26  현금흐름표 [abstract]          투자활동현금흐름          기타무형자산의 취득       5,000,000.0
27  현금흐름표 [abstract]          투자활동현금흐름            무형자산의 취득               nan
28  현금흐름표 [abstract]          투자활동현금흐름             보증금의 증가  14,644,472,000.0
29  현금흐름표 [abstract]          투자활동현금흐름      사업결합으로 인한 현금유출               0.0
30  현금흐름표 [abstract]          재무활동현금흐름                None   5,756,175,318.0
31  현금흐름표 [abstract]          재무활동현금흐름           단기차입금의 증가   1,014,363,432.0
32  현금흐름표 [abstract]          재무활동현금흐름          금융리스부채의 증가               nan
33  현금흐름표 [abstract]          재무활동현금흐름            전환사채의 증가   6,000,000,000.0
34  현금흐름표 [abstract]          재무활동현금흐름                유상증자   5,977,667,785.0
35  현금흐름표 [abstract]          재무활동현금흐름           단기차입금의 상환   3,801,800,930.0
36  현금흐름표 [abstract]          재무활동현금흐름           금융리스부채의상환     434,054,969.0
37  현금흐름표 [abstract]          재무활동현금흐름            전환사채의 감소   3,000,000,000.0
38  현금흐름표 [abstract]          재무활동현금흐름        신주인수권부사채의 상환               nan
39  현금흐름표 [abstract]  현금및현금성자산의순증가(감소)                None  -6,810,119,751.0
40  현금흐름표 [abstract]        기초현금및현금성자산                None  10,034,226,743.0
41  현금흐름표 [abstract]        기말현금및현금성자산                None   3,224,106,992.0

   20180101-20181231 20170101-20171231
           (연결재무제표,)         (연결재무제표,)
0   -1,843,697,436.0  -6,515,452,187.0
1  -11,600,802,176.0 -15,088,717,271.0
2   11,058,914,347.0  11,139,266,536.0
3   -1,092,294,789.0  -2,629,164,616.0
4    1,080,280,463.0     920,116,427.0
5      441,782,743.0     601,820,053.0
6      848,012,538.0     255,133,210.0
7    5,280,236,719.0  -8,273,909,265.0
8       18,000,227.0  15,727,861,909.0
9    7,487,100,000.0     242,384,414.0
10   4,594,427,958.0       4,244,454.0
11               nan               nan
12  16,438,734,328.0               nan
13               nan               nan
14   6,000,000,000.0               nan
15   2,030,000,000.0               nan
16     105,165,780.0      54,007,283.0
17     517,846,000.0     373,342,990.0
18       4,665,887.0      47,878,902.0
19      14,000,000.0               nan
20  16,271,784,291.0               nan
21               nan   1,000,000,000.0
22   1,188,326,000.0               nan
23               nan   2,382,548,169.0
24         263,820.0               nan
25     607,637,350.0   1,413,624,813.0
26     430,000,000.0               nan
27               nan      53,870,000.0
28   1,403,692,000.0               nan
29               nan  19,873,586,235.0
30   5,371,367,390.0  15,268,693,486.0
31   4,597,003,932.0               nan
32               nan   1,010,880,625.0
33      19,000,000.0               nan
34     998,331,045.0  18,978,078,880.0
35               nan     283,113,327.0
36     242,967,587.0     437,152,692.0
37               nan               nan
38               nan   4,000,000,000.0
39   8,807,906,673.0     479,332,034.0
40   1,226,320,070.0     746,988,036.0
41  10,034,226,743.0   1,226,320,070.0

In [184]:
df_cf.to_csv('data/현금흐름표.csv', index = False)

In [191]:
df_cf_1 = df_cf.iloc[:,[1,6,7,8]]
df_cf_1.columns = ['', df_cf_1.columns[1][0], df_cf_1.columns[2][0], df_cf_1.columns[3][0]]
df_cf_1 = df_cf_1.T
df_cf_1 = df_cf_1.rename(columns=df_cf_1.iloc[0])
df_cf_1 = df_cf_1.drop(df_cf_1.index[0])
df_cf_1 = df_cf_1.reset_index().rename(columns={'index':'date'})
df_cf_1['date'] = df_cf_1['date'].str[9:]
print(df_cf_1.shape)
df_cf_1.head()

(3, 43)

,date,영업활동현금흐름,당기순이익(손실),당기순이익조정을 위한 가감,영업활동으로인한자산ㆍ부채의변동,이자수취,이자지급,법인세환급(납부),투자활동현금흐름,단기금융상품의감소,...,금융리스부채의 증가,전환사채의 증가,유상증자,단기차입금의 상환,금융리스부채의상환,전환사채의 감소,신주인수권부사채의 상환,현금및현금성자산의순증가(감소),기초현금및현금성자산,기말현금및현금성자산
0,20191231,"-6,256,061,272.0","-19,846,313,537.0","16,482,969,417.0","-2,203,657,409.0","59,581,132.0","835,209,069.0","-86,568,194.0","-6,310,233,797.0","12,000,000.0",...,NaN,"6,000,000,000.0","5,977,667,785.0","3,801,800,930.0","434,054,969.0","3,000,000,000.0",NaN,"-6,810,119,751.0","10,034,226,743.0","3,224,106,992.0"
1,20181231,"-1,843,697,436.0","-11,600,802,176.0","11,058,914,347.0","-1,092,294,789.0","1,080,280,463.0","441,782,743.0","848,012,538.0","5,280,236,719.0","18,000,227.0",...,NaN,"19,000,000.0","998,331,045.0",NaN,"242,967,587.0",NaN,NaN,"8,807,906,673.0","1,226,320,070.0","10,034,226,743.0"
2,20171231,"-6,515,452,187.0","-15,088,717,271.0","11,139,266,536.0","-2,629,164,616.0","920,116,427.0","601,820,053.0","255,133,210.0","-8,273,909,265.0","15,727,861,909.0",...,"1,010,880,625.0",NaN,"18,978,078,880.0","283,113,327.0","437,152,692.0",NaN,"4,000,000,000.0","479,332,034.0","746,988,036.0","1,226,320,070.0"

In [203]:
data_total = pd.merge(df_cis_1, df_bs_1, on = 'date')
data_total = pd.merge(data_total, df_cf_1, on = 'date')
print(data_total.shape)
data_total

(3, 109)

,date,매출액,매출원가,매출총이익,판매비와관리비,영업이익(손실),영업외수익,금융수익,종속기업및관계기업이익,기타수익,...,금융리스부채의 증가,전환사채의 증가,유상증자,단기차입금의 상환,금융리스부채의상환,전환사채의 감소,신주인수권부사채의 상환,현금및현금성자산의순증가(감소),기초현금및현금성자산,기말현금및현금성자산
0,20191231,"12,690,903,987.0","12,607,067,912.0","83,836,075.0","3,863,460,724.0","-3,779,624,649.0","3,976,742,997.0","1,204,645,697.0","2,401,030,418.0","371,066,882.0",...,NaN,"6,000,000,000.0","5,977,667,785.0","3,801,800,930.0","434,054,969.0","3,000,000,000.0",NaN,"-6,810,119,751.0","10,034,226,743.0","3,224,106,992.0"
1,20181231,"26,187,470,807.0","24,916,951,370.0","1,270,519,437.0","5,214,421,708.0","-3,943,902,271.0","1,116,468,403.0","738,307,926.0","11,044,142.0","367,116,335.0",...,NaN,"19,000,000.0","998,331,045.0",NaN,"242,967,587.0",NaN,NaN,"8,807,906,673.0","1,226,320,070.0","10,034,226,743.0"
2,20171231,"14,262,299,673.0","15,083,677,830.0","-821,378,157.0","6,019,047,667.0","-6,840,425,824.0","2,140,222,096.0","1,249,748,914.0","750,398,099.0","140,075,083.0",...,"1,010,880,625.0",NaN,"18,978,078,880.0","283,113,327.0","437,152,692.0",NaN,"4,000,000,000.0","479,332,034.0","746,988,036.0","1,226,320,070.0"